### GET skip log
POST http://127.0.0.1:8081/api/ping/wangwu

### GET
POST http://127.0.0.1:8081/api/ping/zhangsan?age=18
AuthToken: token123456
Content-Type: application/json

{
    "score": 100,
    "address": {
        "home":"beijing",
        "school":"hainan"
    }
}

### GET 
POST http://127.0.0.1:8081/v1/ping/wangwu?age=20
Content-Type: application/x-www-form-urlencoded

score=100&address=beijing

